import { StyleSheet } from 'react-native';

const colors = {
  sand: '#F1ECE2',
  sandDeep: '#E8E2D5',
  lime: '#D4F82A',
  coral: '#FF6B4A',
  ink: '#18181B',
  muted: '#71717A',
  glass: 'rgba(255, 255, 255, 0.68)',
  border: 'rgba(0, 0, 0, 0.06)',
  white: '#FFFFFF',
};

const shadow = {
  shadowColor: '#000',
  shadowOpacity: 0.04,
  shadowRadius: 12,
  shadowOffset: { width: 0, height: 5 },
  elevation: 2,
};

export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: colors.sand },
  content: { padding: 20, paddingBottom: 48, maxWidth: 760, width: '100%', alignSelf: 'center' },
  header: { height: 72, paddingHorizontal: 20, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: colors.glass, borderBottomWidth: 1, borderBottomColor: colors.border },
  logo: { flexDirection: 'row', alignItems: 'center' },
  logoMark: { backgroundColor: colors.coral, width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center' },
  logoGlyph: { color: colors.white, fontSize: 24, fontWeight: '800', lineHeight: 28 },
  logoText: { color: colors.ink, fontSize: 22, fontWeight: '800', marginLeft: 8, letterSpacing: -0.6 },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 16 },
  headerRole: { color: '#277B8A', fontSize: 10, fontWeight: '800', letterSpacing: 1 },
  headerRoleGreen: { color: '#3E7D53', fontSize: 10, fontWeight: '800', letterSpacing: 1 },
  logout: { color: colors.muted, fontSize: 13, fontWeight: '700' },
  overline: { color: '#277B8A', fontSize: 10, fontWeight: '800', letterSpacing: 1.4, marginTop: 22 },
  overlineGreen: { color: '#3E7D53', fontSize: 10, fontWeight: '800', letterSpacing: 1.4, marginTop: 22 },
  pageTitle: { color: colors.ink, fontSize: 30, fontWeight: '800', letterSpacing: -0.8, marginTop: 8 },
  pageSubtitle: { color: colors.muted, fontSize: 15, lineHeight: 22, marginTop: 8, maxWidth: 560 },
  searchBox: { height: 54, backgroundColor: colors.glass, borderWidth: 1, borderColor: colors.border, borderRadius: 27, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 17, marginTop: 24, ...shadow },
  searchIcon: { color: colors.ink, fontSize: 25, marginRight: 9 },
  searchInput: { flex: 1, color: colors.ink, fontSize: 14 },
  clear: { color: '#277B8A', fontSize: 12, fontWeight: '700' },
  suggestion: { backgroundColor: '#FFF1D6', borderRadius: 24, padding: 13, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 8 },
  suggestionText: { color: '#725B32', fontSize: 13 },
  suggestionStrong: { fontWeight: '800', textDecorationLine: 'underline' },
  suggestionAction: { color: '#A26421', fontSize: 12, fontWeight: '800' },
  categoryRow: { marginTop: 18, flexGrow: 0 },
  pill: { paddingHorizontal: 16, paddingVertical: 10, borderRadius: 50, backgroundColor: colors.glass, borderWidth: 1, borderColor: colors.border, marginRight: 8 },
  pillActive: { backgroundColor: colors.lime, borderColor: colors.lime },
  pillText: { color: colors.muted, fontSize: 12, fontWeight: '700' },
  pillTextActive: { color: colors.ink },
  section: { marginTop: 28 },
  sectionTitle: { color: colors.ink, fontSize: 19, fontWeight: '800', marginBottom: 13 },
  serviceRailCard: { backgroundColor: colors.ink, borderRadius: 26, padding: 18, width: 190, minHeight: 176, marginRight: 12, ...shadow },
  railCategory: { color: colors.lime, fontSize: 10, fontWeight: '800', textTransform: 'uppercase' },
  railTitle: { color: colors.white, fontSize: 16, fontWeight: '800', marginTop: 17 },
  railProvider: { color: '#C7C7CA', fontSize: 12, marginTop: 5 },
  railPrice: { color: colors.lime, fontSize: 14, fontWeight: '800', marginTop: 22 },
  serviceCard: { backgroundColor: colors.glass, borderRadius: 26, borderWidth: 1, borderColor: colors.border, padding: 17, marginBottom: 12, ...shadow },
  cardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  serviceCategory: { color: colors.ink, backgroundColor: colors.lime, paddingHorizontal: 10, paddingVertical: 5, borderRadius: 50, fontSize: 10, fontWeight: '800', textTransform: 'uppercase' },
  rating: { color: '#A26421', fontSize: 12, fontWeight: '700' },
  serviceTitle: { color: colors.ink, fontSize: 17, fontWeight: '800', marginTop: 10 },
  provider: { color: colors.muted, fontSize: 13, marginTop: 3 },
  description: { color: '#64646B', fontSize: 13, lineHeight: 19, marginTop: 10 },
  serviceBottom: { borderTopWidth: 1, borderTopColor: colors.border, marginTop: 14, paddingTop: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  price: { color: '#3E7D53', fontSize: 13, fontWeight: '800' },
  link: { color: '#277B8A', fontSize: 12, fontWeight: '800' },
  empty: { padding: 24, borderWidth: 1, borderColor: colors.border, borderRadius: 26, alignItems: 'center', backgroundColor: colors.glass },
  emptyTitle: { color: colors.ink, fontWeight: '800' },
  emptyText: { color: colors.muted, fontSize: 13, marginTop: 5 },
  metricGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', gap: 9, marginTop: 24 },
  metric: { width: '31.5%', minHeight: 106, borderRadius: 26, padding: 15, justifyContent: 'space-between', ...shadow },
  metricWide: { width: '100%', minHeight: 88 },
  metricblue: { backgroundColor: '#D9F0F3' },
  metricorange: { backgroundColor: '#FFE0D7' },
  metricgreen: { backgroundColor: colors.lime },
  metricdark: { backgroundColor: colors.ink },
  metricLabel: { color: colors.muted, fontSize: 11, fontWeight: '800' },
  metricValue: { color: colors.ink, fontSize: 32, fontWeight: '800' },
  greenButton: { backgroundColor: colors.lime, paddingVertical: 15, paddingHorizontal: 18, borderRadius: 50, alignItems: 'center', marginTop: 17, ...shadow },
  greenButtonText: { color: colors.ink, fontSize: 14, fontWeight: '800' },
  budgetCard: { backgroundColor: colors.glass, borderRadius: 26, borderWidth: 1, borderColor: colors.border, padding: 17, marginBottom: 12, ...shadow },
  budgetClient: { color: colors.ink, fontSize: 16, fontWeight: '800' },
  budgetDate: { color: '#8B9290', fontSize: 12, marginTop: 3 },
  status: { paddingHorizontal: 11, paddingVertical: 6, borderRadius: 50, fontSize: 10, fontWeight: '800', textTransform: 'uppercase' },
  statussolicitado: { color: '#277B8A', backgroundColor: '#D9F0F3' },
  statuspendente: { color: '#9B554B', backgroundColor: '#FFE0D7' },
  statusrealizado: { color: colors.ink, backgroundColor: colors.lime },
  statusrecusado: { color: '#9B554B', backgroundColor: '#F5DFDC' },
  budgetService: { color: '#4F5954', fontSize: 14, fontWeight: '700', marginTop: 14 },
  budgetBottom: { borderTopWidth: 1, borderTopColor: colors.border, marginTop: 14, paddingTop: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  budgetValue: { color: colors.ink, fontSize: 17, fontWeight: '800' },
  actionRow: { flexDirection: 'row', gap: 15 },
  actionText: { color: '#3E7D53', fontSize: 12, fontWeight: '800' },
  actionTextMuted: { color: '#9B554B', fontSize: 12, fontWeight: '800' },
  loginPage: { flexGrow: 1, backgroundColor: colors.sand, justifyContent: 'center', alignItems: 'center', padding: 22 },
  loginShell: { width: '100%', maxWidth: 920, alignItems: 'center', justifyContent: 'center' },
  loginIntro: { width: '100%', maxWidth: 440, alignItems: 'center', marginBottom: 28 },
  eyebrow: { color: '#9B554B', fontSize: 10, fontWeight: '800', letterSpacing: 1.5, marginTop: 25, textAlign: 'center' },
  loginTitle: { color: colors.ink, fontSize: 36, lineHeight: 41, fontWeight: '800', marginTop: 12, textAlign: 'center' },
  loginSubtitle: { color: colors.muted, fontSize: 15, lineHeight: 22, marginTop: 10, textAlign: 'center', maxWidth: 390 },
  loginCard: { backgroundColor: colors.glass, borderRadius: 30, padding: 24, width: '100%', maxWidth: 410, borderWidth: 1, borderColor: colors.border, ...shadow },
  cardTitle: { color: colors.ink, fontSize: 21, fontWeight: '800', marginBottom: 8 },
  loginChoiceSubtitle: { color: colors.muted, fontSize: 14, marginBottom: 19 },
  label: { color: colors.ink, fontSize: 12, fontWeight: '800', marginBottom: 7, marginTop: 12 },
  input: { backgroundColor: 'rgba(255,255,255,0.7)', borderWidth: 1, borderColor: colors.border, borderRadius: 50, minHeight: 48, paddingHorizontal: 16, color: colors.ink, fontSize: 14 },
  roleLabel: { color: '#8B9290', fontSize: 10, fontWeight: '800', letterSpacing: 1.2, marginTop: 22, marginBottom: 9 },
  primaryButton: { backgroundColor: colors.lime, minHeight: 52, borderRadius: 50, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 9 },
  primaryButtonSmall: { backgroundColor: colors.lime, paddingHorizontal: 18, paddingVertical: 13, borderRadius: 50 },
  primaryButtonText: { color: colors.ink, fontSize: 14, fontWeight: '800' },
  buttonArrow: { color: colors.ink, fontSize: 20 },
  secondaryButton: { backgroundColor: colors.ink, minHeight: 52, borderRadius: 50, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 9 },
  secondaryButtonText: { color: colors.white, fontSize: 14, fontWeight: '800' },
  buttonArrowDark: { color: colors.lime, fontSize: 20 },
  choiceIcon: { width: 32, height: 32, borderRadius: 16, backgroundColor: 'rgba(255,255,255,0.65)', alignItems: 'center', justifyContent: 'center', marginRight: 8 },
  backChoice: { flexDirection: 'row', alignItems: 'center', gap: 7, marginBottom: 18 },
  backChoiceText: { color: colors.muted, fontSize: 13, fontWeight: '700' },
  demoText: { textAlign: 'center', color: '#8B9290', fontSize: 11, marginTop: 17, lineHeight: 16 },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(24,24,27,0.55)', justifyContent: 'flex-end' },
  modalCard: { backgroundColor: colors.sand, padding: 24, borderTopLeftRadius: 30, borderTopRightRadius: 30 },
  modalEyebrow: { color: '#277B8A', fontSize: 10, fontWeight: '800', letterSpacing: 1.2 },
  modalTitle: { color: colors.ink, fontSize: 22, fontWeight: '800', marginTop: 9 },
  modalProvider: { color: colors.muted, fontSize: 13, marginTop: 4, marginBottom: 18 },
  messageInput: { minHeight: 100, paddingTop: 13, textAlignVertical: 'top', borderRadius: 24 },
  modalActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 9, marginTop: 16 },
  cancelButton: { paddingHorizontal: 16, paddingVertical: 13 },
  cancelText: { color: colors.muted, fontSize: 13, fontWeight: '800' },
});
