import { StyleSheet } from "react-native";


export const styles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: "#18181B",
  },
  content: {
    padding: 24,
    paddingBottom: 48,
  },
  header: {
    height: 76,
    paddingHorizontal: 24,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#18181B",
    borderBottomWidth: 1,
    borderBottomColor: "#27272A",
  },
  logo: {
    flexDirection: "row",
    alignItems: "center",
  },
  logoMark: {
    backgroundColor: "#CCFF00",
    width: 32,
    height: 32,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  logoGlyph: {
    color: "#18181B",
    fontSize: 20,
    fontWeight: "900",
  },
  logoText: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "800",
    marginLeft: 10,
    letterSpacing: -0.6,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 18,
  },
  headerRole: {
    color: "#38BDF8",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1,
  },
  headerRoleGreen: {
    color: "#4ADE80",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1,
  },
  logoutButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  logout: {
    color: "#A1A1AA",
    fontSize: 13,
    fontWeight: "700",
  },
  loginPage: {
    flexGrow: 1,
    backgroundColor: "#09090B",
    padding: 24,
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  loginOrb: {
    position: "absolute",
    borderRadius: 999,
    opacity: 0.15,
  },
  loginOrbMint: {
    width: 300,
    height: 300,
    backgroundColor: "#4ADE80",
    top: -50,
    left: -50,
  },
  loginOrbBlue: {
    width: 350,
    height: 350,
    backgroundColor: "#38BDF8",
    bottom: -100,
    right: -50,
  },
  loginOrbPeach: {
    width: 250,
    height: 250,
    backgroundColor: "#FB923C",
    top: "40%",
    left: "30%",
  },
  loginLayout: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 48,
    maxWidth: 960,
    width: "100%",
  },
  loginLayoutMobile: {
    flexDirection: "column",
    gap: 24,
  },

  /* GLASSMORPHISM AQUI*/
  glassContainerLeft: {
    borderRadius: 24,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.18)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    maxWidth: 440,
    width: "100%",
  },
  glassBlur: {
    padding: 32,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
  },

  loginIntro: {
    justifyContent: "center",
  },
  loginIntroMobile: {
    alignItems: "flex-start",
  },
  eyebrow: {
    color: "#CCFF00",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.5,
    marginTop: 28,
  },
  loginTitle: {
    color: "#FFFFFF",
    fontSize: 38,
    lineHeight: 44,
    fontWeight: "800",
    marginTop: 12,
    letterSpacing: -0.5,
  },
  loginTitleMobile: {
    fontSize: 30,
    lineHeight: 36,
  },
  loginSubtitle: {
    color: "#A1A1AA",
    fontSize: 15,
    lineHeight: 22,
    marginTop: 12,
  },
  loginSubtitleMobile: {
    fontSize: 14,
    lineHeight: 20,
  },
  loginTrust: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 24,
  },
  loginTrustText: {
    color: "#A1A1AA",
    fontSize: 13,
    fontWeight: "600",
  },
  loginCard: {
    backgroundColor: "#18181B",
    borderRadius: 24,
    padding: 32,
    borderWidth: 1,
    borderColor: "#27272A",
    maxWidth: 420,
    width: "100%",
  },
  loginCardMobile: {
    padding: 24,
  },
  cardTitle: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "800",
    marginBottom: 6,
  },
  loginChoiceSubtitle: {
    color: "#71717A",
    fontSize: 14,
    marginBottom: 20,
  },
  backChoice: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 16,
  },
  backChoiceText: {
    color: "#71717A",
    fontSize: 13,
    fontWeight: "600",
  },
  label: {
    color: "#A1A1AA",
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 6,
    marginTop: 14,
  },
  input: {
    backgroundColor: "#09090B",
    borderWidth: 1,
    borderColor: "#27272A",
    borderRadius: 12,
    minHeight: 48,
    paddingHorizontal: 16,
    color: "#FFFFFF",
    fontSize: 14,
  },
  loginButtonWrap: {
    marginTop: 12,
    position: "relative",
  },
  loginButtonRing: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#CCFF00",
  },
  loginButtonRingDark: {
    borderColor: "#27272A",
  },
  primaryButton: {
    backgroundColor: "#CCFF00",
    minHeight: 50,
    borderRadius: 12,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  primaryButtonText: {
    color: "#18181B",
    fontSize: 15,
    fontWeight: "800",
  },
  buttonArrow: {
    color: "#18181B",
    fontSize: 18,
    fontWeight: "800",
  },
  secondaryButton: {
    backgroundColor: "#27272A",
    minHeight: 50,
    borderRadius: 12,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  secondaryButtonText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "800",
  },
  buttonArrowDark: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "800",
  },
  choiceIcon: {
    marginRight: 8,
  },
  loginButtonPressed: {
    opacity: 0.85,
  },
  demoText: {
    textAlign: "center",
    color: "#71717A",
    fontSize: 11,
    marginTop: 16,
    lineHeight: 16,
  },
  overline: {
    color: "#38BDF8",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.4,
    marginTop: 12,
  },
  overlineGreen: {
    color: "#4ADE80",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.4,
    marginTop: 12,
  },
  pageTitle: {
    color: "#FFFFFF",
    fontSize: 30,
    fontWeight: "800",
    letterSpacing: -0.8,
    marginTop: 6,
  },
  pageSubtitle: {
    color: "#A1A1AA",
    fontSize: 15,
    lineHeight: 22,
    marginTop: 6,
  },
  searchBox: {
    height: 52,
    backgroundColor: "#09090B",
    borderWidth: 1,
    borderColor: "#27272A",
    borderRadius: 14,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    marginTop: 20,
  },
  searchIcon: {
    marginRight: 10,
  },
  searchInput: {
    flex: 1,
    color: "#FFFFFF",
    fontSize: 14,
  },
  clear: {
    color: "#A1A1AA",
    fontSize: 12,
    fontWeight: "700",
  },
  suggestion: {
    backgroundColor: "#27272A",
    borderRadius: 10,
    padding: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 8,
  },
  suggestionText: {
    color: "#A1A1AA",
    fontSize: 13,
  },
  suggestionStrong: {
    color: "#FFFFFF",
    fontWeight: "800",
  },
  suggestionAction: {
    color: "#CCFF00",
    fontSize: 12,
    fontWeight: "800",
  },
  categoryRow: {
    marginTop: 18,
    flexGrow: 0,
  },
  pill: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "#27272A",
    marginRight: 8,
  },
  pillActive: {
    backgroundColor: "#CCFF00",
  },
  pillText: {
    color: "#A1A1AA",
    fontSize: 13,
    fontWeight: "700",
  },
  pillTextActive: {
    color: "#18181B",
  },
  section: {
    marginTop: 28,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  sectionTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "800",
  },
  arrowGroup: {
    flexDirection: "row",
    gap: 8,
  },
  arrowButton: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: "#27272A",
    justifyContent: "center",
    alignItems: "center",
  },
  arrowButtonDisabled: {
    opacity: 0.3,
  },
  serviceRailCard: {
    backgroundColor: "#27272A",
    borderRadius: 16,
    padding: 18,
    width: 200,
    marginRight: 12,
  },
  railCategory: {
    color: "#CCFF00",
    fontSize: 11,
    fontWeight: "800",
  },
  railTitle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "800",
    marginTop: 12,
  },
  railProvider: {
    color: "#A1A1AA",
    fontSize: 13,
    marginTop: 4,
  },
  railPrice: {
    color: "#4ADE80",
    fontSize: 14,
    fontWeight: "800",
    marginTop: 18,
  },
  serviceCard: {
    backgroundColor: "#27272A",
    borderRadius: 16,
    padding: 18,
    marginBottom: 12,
  },
  cardTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  serviceCategory: {
    color: "#38BDF8",
    fontSize: 11,
    fontWeight: "800",
  },
  rating: {
    color: "#FACC15",
    fontSize: 12,
    fontWeight: "700",
  },
  serviceTitle: {
    color: "#FFFFFF",
    fontSize: 17,
    fontWeight: "800",
    marginTop: 8,
  },
  provider: {
    color: "#A1A1AA",
    fontSize: 13,
    marginTop: 2,
  },
  description: {
    color: "#D4D4D8",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 8,
  },
  serviceBottom: {
    borderTopWidth: 1,
    borderTopColor: "#3F3F46",
    marginTop: 14,
    paddingTop: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  price: {
    color: "#4ADE80",
    fontSize: 14,
    fontWeight: "800",
  },
  link: {
    color: "#38BDF8",
    fontSize: 13,
    fontWeight: "700",
  },
  empty: {
    padding: 24,
    borderWidth: 1,
    borderColor: "#27272A",
    borderRadius: 16,
    alignItems: "center",
  },
  emptyTitle: {
    color: "#FFFFFF",
    fontWeight: "800",
  },
  emptyText: {
    color: "#71717A",
    fontSize: 13,
    marginTop: 4,
  },
  metricGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 20,
  },
  metric: {
    flex: 1,
    minWidth: "30%",
    minHeight: 88,
    borderRadius: 16,
    padding: 14,
    justifyContent: "space-between",
  },
  metricWide: {
    minWidth: "100%",
  },
  metricblue: { backgroundColor: "rgba(56, 189, 248, 0.15)" },
  metricorange: { backgroundColor: "rgba(251, 146, 60, 0.15)" },
  metricgreen: { backgroundColor: "rgba(74, 222, 128, 0.15)" },
  metricdark: { backgroundColor: "#27272A" },
  metricLabel: { color: "#A1A1AA", fontSize: 11, fontWeight: "800" },
  metricValue: { color: "#FFFFFF", fontSize: 24, fontWeight: "800" },
  greenButton: {
    backgroundColor: "#4ADE80",
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 16,
  },
  greenButtonText: { color: "#18181B", fontSize: 14, fontWeight: "800" },
  budgetCard: {
    backgroundColor: "#27272A",
    borderRadius: 16,
    padding: 18,
    marginBottom: 12,
  },
  budgetClient: { color: "#FFFFFF", fontSize: 16, fontWeight: "800" },
  budgetDate: { color: "#71717A", fontSize: 12, marginTop: 2 },
  status: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    fontSize: 10,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  statussolicitado: { color: "#38BDF8", backgroundColor: "rgba(56, 189, 248, 0.15)" },
  statuspendente: { color: "#FB923C", backgroundColor: "rgba(251, 146, 60, 0.15)" },
  statusrealizado: { color: "#4ADE80", backgroundColor: "rgba(74, 222, 128, 0.15)" },
  statusrecusado: { color: "#F87171", backgroundColor: "rgba(248, 113, 113, 0.15)" },
  budgetService: {
    color: "#D4D4D8",
    fontSize: 14,
    fontWeight: "700",
    marginTop: 12,
  },
  budgetBottom: {
    borderTopWidth: 1,
    borderTopColor: "#3F3F46",
    marginTop: 14,
    paddingTop: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  budgetValue: { color: "#FFFFFF", fontSize: 16, fontWeight: "800" },
  actionRow: { flexDirection: "row", gap: 14 },
  actionText: { color: "#4ADE80", fontSize: 13, fontWeight: "800" },
  actionTextMuted: { color: "#F87171", fontSize: 13, fontWeight: "800" },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.75)",
    justifyContent: "flex-end",
  },
  modalCard: {
    backgroundColor: "#18181B",
    padding: 24,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
  },
  modalEyebrow: {
    color: "#38BDF8",
    fontSize: 11,
    fontWeight: "800",
  },
  modalTitle: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "800",
    marginTop: 6,
  },
  modalProvider: {
    color: "#A1A1AA",
    fontSize: 13,
    marginTop: 4,
    marginBottom: 16,
  },
  messageInput: {
    minHeight: 90,
    paddingTop: 12,
    textAlignVertical: "top",
  },
  attachButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 12,
  },
  attachText: {
    color: "#CCFF00",
    fontSize: 13,
    fontWeight: "700",
  },
  attachmentPreview: {
    width: "100%",
    height: 120,
    borderRadius: 12,
    marginTop: 12,
  },
  modalActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 12,
    marginTop: 20,
  },
  cancelButton: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  cancelText: {
    color: "#A1A1AA",
    fontSize: 14,
    fontWeight: "700",
  },
  primaryButtonSmall: {
    backgroundColor: "#CCFF00",
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 10,
  },
});