import { StyleSheet } from "react-native";

export const registerStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#09090B",
  },
  inner: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 24,
  },
  cardWrap: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  card: {
    width: "80%",
    maxWidth: 440,
    minHeight: 420,
    backgroundColor: "#18181B",
    borderRadius: 18,
    padding: 22,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    shadowColor: "#000",
    shadowOpacity: 0.28,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 18,
    elevation: 8,
    overflow: "hidden",
  },
  floatingIcon: {
    position: "absolute",
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: "rgba(24,24,27,0.92)",
    borderWidth: 1,
    borderColor: "rgba(204,255,0,0.28)",
    alignItems: "center",
    justifyContent: "center",
  },
  stepEyebrow: {
    color: "#CCFF00",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.4,
  },
  stepTitle: {
    color: "#FFFFFF",
    fontSize: 26,
    lineHeight: 32,
    fontWeight: "800",
    marginTop: 8,
    letterSpacing: -0.4,
  },
  stepSubtitle: {
    color: "#A1A1AA",
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
    marginBottom: 18,
  },
  roleRow: {
    gap: 10,
  },
  roleButton: {
    minHeight: 64,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#27272A",
    backgroundColor: "#09090B",
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  roleButtonActive: {
    borderColor: "#CCFF00",
    backgroundColor: "rgba(204,255,0,0.08)",
  },
  roleIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "#27272A",
    alignItems: "center",
    justifyContent: "center",
  },
  roleIconActive: {
    backgroundColor: "#CCFF00",
  },
  roleLabel: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "800",
  },
  roleHint: {
    color: "#71717A",
    fontSize: 12,
    marginTop: 2,
  },
  searchBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#27272A",
    backgroundColor: "#09090B",
    paddingHorizontal: 12,
    marginBottom: 12,
  },
  searchInput: {
    flex: 1,
    color: "#FFFFFF",
    fontSize: 14,
  },
  chips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "#27272A",
  },
  chipActive: {
    backgroundColor: "#CCFF00",
  },
  chipText: {
    color: "#D4D4D8",
    fontSize: 12,
    fontWeight: "700",
  },
  chipTextActive: {
    color: "#18181B",
  },
  otherInput: {
    marginTop: 14,
    minHeight: 48,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#27272A",
    backgroundColor: "#09090B",
    paddingHorizontal: 14,
    color: "#FFFFFF",
    fontSize: 14,
  },
  errorText: {
    color: "#F87171",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 8,
  },
  input: {
    minHeight: 52,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#27272A",
    backgroundColor: "#09090B",
    paddingHorizontal: 16,
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "700",
    letterSpacing: 0.4,
  },
  paginator: {
    flexDirection: "row",
    alignItems: "center",
    columnGap: 20,
    marginTop: 22,
    position: "relative",
  },
  progressBar: {
    position: "absolute",
    height: 26,
    borderRadius: 13,
    backgroundColor: "#CCFF00",
    zIndex: -1,
  },
  dot: {
    width: 10,
    height: 10,
    borderRadius: 10,
  },
  controls: {
    flexDirection: "row",
    marginTop: 22,
    width: "100%",
    height: 55,
  },
  mainButton: {
    position: "absolute",
    right: "5%",
    height: 55,
    borderRadius: 30,
    backgroundColor: "#CCFF00",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  backButton: {
    position: "absolute",
    left: "5%",
    height: 55,
    borderRadius: 30,
    backgroundColor: "#27272A",
    alignItems: "center",
    justifyContent: "center",
  },
  mainButtonText: {
    color: "#18181B",
    fontSize: 17,
    fontWeight: "800",
  },
  backButtonText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "700",
  },
  check: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#18181B",
    alignItems: "center",
    justifyContent: "center",
  },
  close: {
    position: "absolute",
    top: 18,
    left: 18,
    zIndex: 4,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  closeText: {
    color: "#A1A1AA",
    fontSize: 13,
    fontWeight: "700",
  },
});
